<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Overpass QL</string>
    <key>scopeName</key>
    <string>source.overpass</string>
    <key>fileTypes</key>
    <array>
        <string>overpass</string>
    </array>
    <key>patterns</key>
    <array>
        <!--set names-->
        <dict>
            <key>match</key>
            <string>(?<=\.)([\w|\d]+)</string>
            <key>name</key>
            <string>entity.name.type.overpass</string>
        </dict>
        <!--recursion-->
        <dict>
            <key>match</key>
            <string>(<|>)</string>
            <key>name</key>
            <string>keyword.operator.overpass</string>
        </dict>
        <!--header-->
        <dict>
            <key>match</key>
            <string>(json|xml|csv|custom|popup|timeout|maxsize|bbox)</string>
            <key>name</key>
            <string>keyword.overpass</string>
        </dict>
        <!--osm types-->
        <dict>
            <key>match</key>
            <string>(relation|rel|way|node)</string>
            <key>name</key>
            <string>variable.parameter</string>
        </dict>
        <!--filters-->
        <dict>
            <key>match</key>
            <string>(area|around|changed|convert|count_tags|count_members|date|foreach|id|if|is_date|is_in|is_number|is_tag|make|map_to_area|max|min|newer|number|pivot|poly|sum|uid|user|type)</string>
            <key>name</key>
            <string>entity.name.function.overpass</string>
        </dict>
        <!--out-->
        <dict> 
            <key>match</key>
            <string>(?<!\[)out\s*(?:(?:body|count|ids|meta|skel|tags|geom|bb|center|qt|asc|(?:\d+)?)\s*)*</string>
            <key>name</key>
            <string>keyword.overpass</string>
        </dict>
        <!--Constants-->
        <!--booleans-->
        <dict>
            <key>name</key>
            <string>constant.language.overpass</string>
            <key>match</key>
            <string>(true|false)</string>
        </dict>
        <!--numeric-->
        <dict>
            <key>match</key>
            <string>(\d+)</string>
            <key>name</key>
            <string>entity.constant.numeric.overpass</string>
        </dict>
        <!--strings-->
        <dict>  
            <key>name</key>
            <string>string.quoted.single.overpass</string>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
            <key>patterns</key> 
            <array>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.overpass</string>
                    <key>match</key>
                    <string>\\.</string>
                </dict>
            </array>
        </dict>
        <dict>  
            <key>name</key>
            <string>string.quoted.double.overpass</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>patterns</key> 
            <array>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.overpass</string>
                    <key>match</key>
                    <string>\\.</string>
                </dict>
            </array>
        </dict>
        <!--Comments-->
        <!--inline comment-->
        <dict>
            <key>name</key>
            <string>comment.double-slash.overpass</string>
            <key>match</key>
            <string>(\/\/.*)</string>
        </dict>
        <!--block comment-->
        <dict>
            <key>name</key>
            <string>comment.block.overpass</string>
            <key>begin</key>
            <string>\/\*</string>
            <key>end</key>
            <string>\*\/</string>
        </dict>
    </array>
</dict>
</plist>